name: Docker Workflow
on:
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2 
    - name: Build and Run Docker Containers
      shell: bash
      run: |
        docker build -t hello .
        docker run --rm hello
      working-directory: ./
